services:
  data_base_ppp:
    image: mysql:8.0
    container_name: data_base_ppp
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: datasppp
      MYSQL_USER: sppp
      MYSQL_PASSWORD: sppp123
    ports:
      - "3306:3306"
    volumes:
      - volumen_db:/var/lib/mysql
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M

  archivos_ppp:
    image: minio/minio:latest
    container_name: archivos_ppp
    command: server /data --console-address ":9001"
    restart: unless-stopped
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      MINIO_CORS_ALLOWED_ORIGINS: "*"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - volumen_archivos:/data
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 128M

volumes:
  volumen_db:
  volumen_archivos: